BESL.Web/Areas/Administration/Controllers/MatchFixturesController.cs
namespace BESL.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.Matches.Commands.Create;
    using BESL.Application.Matches.Commands.Modify;
    using BESL.Application.Matches.Commands.Delete;
    using BESL.Application.Matches.Queries.GetMatchesForPlayWeek;
    using BESL.Application.Matches.Queries.Modify;
    using BESL.Application.Matches.Commands.AcceptResult;

    public class MatchFixturesController : AdminController
    {
        public async Task<IActionResult> Details(GetMatchesForPlayWeekQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> Create(CreateMatchCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(
                    "~/Areas/Administration/Views/MatchFixtures/Details.cshtml", 
                    await this.Mediator.Send(new GetMatchesForPlayWeekQuery { PlayWeekId = command.PlayWeekId }));
            }
            
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetMatchesForPlayWeekQuery { PlayWeekId = command.PlayWeekId });
        }

        public async Task<IActionResult> Modify(ModifyMatchQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> Modify(ModifyMatchCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(command);
            }

            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetMatchesForPlayWeekQuery { PlayWeekId = command.PlayWeekId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteMatchCommand command, int playWeekId)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetMatchesForPlayWeekQuery { PlayWeekId = playWeekId });
        }

        [HttpPost]
        public async Task<IActionResult> AcceptResult(AcceptMatchResultCommand command, int playWeekId)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetMatchesForPlayWeekQuery { PlayWeekId = playWeekId });
        }
    }
}

BESL.Web/Components/AddMatchFixtureViewComponent.cs
namespace BESL.Web.Components
{
    using System.Threading.Tasks;

    using MediatR;
    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.Matches.Queries.Create;

    public class AddMatchFixtureViewComponent : ViewComponent
    {
        private readonly IMediator mediator;

        public AddMatchFixtureViewComponent(IMediator mediator) => this.mediator = mediator;

        public async Task<IViewComponentResult> InvokeAsync(int playWeekId)
            => this.View(await this.mediator.Send(new CreateMatchQuery { PlayWeekId = playWeekId }));
    }
}

BESL.Web/Controllers/MatchesController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.Matches.Queries.Details;
    using BESL.Application.Matches.Queries.EditMatchResult;
    using BESL.Application.Matches.Commands.EditMatchResult;

    [Authorize]
    public class MatchesController : BaseController
    {
        [AllowAnonymous]
        public async Task<IActionResult> Details(GetMatchDetailsQuery query)
            => this.View(await this.Mediator.Send(query));

        public async Task<IActionResult> EditResult(EditMatchResultQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> EditResult(EditMatchResultCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetMatchDetailsQuery { Id = command.Id });
        }
    }
}

BESL.Web/Controllers/TeamsController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    using BESL.Application.Teams.Commands.Create;
    using BESL.Application.Teams.Commands.Modify;
    using BESL.Application.Teams.Commands.InvitePlayer;
    using BESL.Application.Teams.Commands.RemovePlayer;
    using BESL.Application.Teams.Commands.TransferOwnership;
    using BESL.Application.Teams.Queries.Details;
    using BESL.Application.Teams.Queries.Modify;
    using BESL.Application.Teams.Queries.GetAllTeamsPaged;
    using BESL.Application.TournamentFormats.Queries.GetAllTournamentFormatsSelectList;
    using static BESL.SharedKernel.GlobalConstants;
    
    [Authorize]
    public class TeamsController : BaseController
    {
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery(Name = "p")]int? page)
        {
            page = (page ?? 1) - 1;

            // Results per page is intentionally used as a constant for testing purposes.
            // In a real life application, the user will be able to select the results
            // he wants to see on a given page.
            var query = new GetAllTeamsPagedQuery { Page = page.Value, PageSize = RESULTS_PER_PAGE_COUNT };

            var viewModel = await this.Mediator.Send(query);
            var pagedList = new StaticPagedList<TeamLookupModel>(
                viewModel.Teams,
                page.Value + 1,
                RESULTS_PER_PAGE_COUNT,
                viewModel.TotalTeamsCount);

            return this.View(pagedList);
        }

        public async Task<IActionResult> Create()
            => this.View(new CreateTeamCommand
            {
                Formats = await this.Mediator.Send(new GetAllTournamentFormatsSelectListQuery())
            });

        [HttpPost]
        public async Task<IActionResult> Create(CreateTeamCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                command.Formats = await this.Mediator.Send(new GetAllTournamentFormatsSelectListQuery());
                return this.View(command);
            }

            var teamId = await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new { Id = teamId });
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(GetTeamDetailsQuery query)
            => this.View(await this.Mediator.Send(query));

        public async Task<IActionResult> Modify(ModifyTeamQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> Modify(ModifyTeamCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(command);
            }

            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetTeamDetailsQuery { Id = command.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Invite(InvitePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Modify), new ModifyTeamQuery { Id = command.TeamId });
        }

        [HttpPost]
        public async Task<IActionResult> RemovePlayer(RemovePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Modify), new ModifyTeamQuery { Id = command.TeamId });
        }

        [HttpPost]
        public async Task<IActionResult> Leave(RemovePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.LocalRedirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> TransferOwnership(TransferTeamOwnershipCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetTeamDetailsQuery { Id = command.TeamId });
        }
    }
}

BESL.Web/Areas/Administration/Views/MatchFixtures/Details.cshtml
@model BESL.Application.Matches.Queries.GetMatchesForPlayWeek.MatchesForPlayWeekViewModel
@using static BESL.SharedKernel.GlobalConstants;
@{
    ViewData["ActivePage"] = ManageAdminNavPages.Tournaments;
    ViewData["Title"] = "Match fixtures";
}

<vc:add-match-fixture play-week-id="@Model.PlayWeekId"></vc:add-match-fixture>
<h5>Week: @Model.WeekAsString</h5>
<table class="table table-sm shadow mt-2">
    <thead>
        <tr>
            <th scope="col">Home Team</th>
            <th scope="col">Away Team</th>
            <th scope="col">Play Date</th>
            <th scope="col" class="text-center">Accept Result</th>
            <th scope="col" class="text-center">Details</th>
            <th scope="col" class="text-center">Modify</th>
            <th scope="col" class="text-center">Remove</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Matches.Count() != 0)
        {
            @foreach (var match in Model.Matches)
            {
                <tr>
                    <td class="align-middle"><a asp-area="" asp-controller="Teams" asp-action="Details" asp-route-id="@match.HomeTeamId"><strong>@match.HomeTeamName</strong></a></td>
                    <td class="align-middle"><a asp-area="" asp-controller="Teams" asp-action="Details" asp-route-id="@match.AwayTeamId"><strong>@match.AwayTeamName</strong></a></td>
                    <td class="align-middle">@match.ScheduledDate.ToString(DATE_HOUR_FORMAT)</td>

                    @if (!match.IsResultConfirmed)
                    {
                        <td class="text-center align-middle">
                            <form asp-controller="MatchFixtures" asp-action="AcceptResult">
                                <input hidden asp-for="@match.Id" name="Id"/>
                                <input hidden asp-for="@Model.PlayWeekId" />
                                <button class="btn btn-sm btn-warning text-white">Accept Result</button>
                            </form>
                        </td>
                    }
                    else
                    {
                        <td class="text-center">Confirmed</td>
                    }

                    <td class="text-center"><a class="btn btn-sm btn-primary text-white" asp-area="" asp-controller="Matches" asp-action="Details" asp-route-Id="@match.Id">Details</a></td>
                    <td class="text-center"><a class="btn btn-sm btn-primary text-white" asp-controller="MatchFixtures" asp-action="Modify" asp-route-MatchId="@match.Id">Modify</a></td>
                    <td class="text-center">
                        <form asp-controller="MatchFixtures" asp-action="Delete">
                            <input hidden asp-for="@match.Id" name="Id" />
                            <input hidden asp-for="@Model.PlayWeekId" />
                            <button class="btn btn-sm btn-danger text-white">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" class="text-center"><h5 class="text-danger">No matches.</h5></td>
            </tr>
        }
    </tbody>
</table>


BESL.Web/Areas/Administration/Views/MatchFixtures/Modify.cshtml
@model BESL.Application.Matches.Commands.Modify.ModifyMatchCommand
@using static BESL.SharedKernel.GlobalConstants;
@{
    ViewData["ActivePage"] = ManageAdminNavPages.Tournaments;
    ViewData["Title"] = "Modify match";
}

<div class="col-md-7">
    <div class="border rounded">
        <h4 class="display-4 mt-2 mx-3">Modify match (Id: @Model.Id)</h4>
        <h4 class="ml-3">@Model.HomeTeamName vs @Model.AwayTeamName</h4>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <form class="mx-3 my-2" method="post" enctype="multipart/form-data">
                    <div class="form-group mb-2">
                        <label asp-for="@Model.HomeTeamScore">Home Team score</label>
                        <select asp-for="@Model.HomeTeamScore" class="form-control form-control-sm">
                            <option selected disabled>Choose...</option>
                            <option value="">N/A</option>
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <span asp-validation-for="@Model.HomeTeamScore" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="@Model.AwayTeamScore">Away Team score</label>
                        <select asp-for="@Model.AwayTeamScore" class="form-control form-control-sm">
                            <option selected disabled>Choose...</option>
                            <option value="">N/A</option>
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <span asp-validation-for="@Model.AwayTeamScore" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="@Model.ScheduledDate">Play date</label>
                        <input type="datetime-local" class="form-control" asp-for="@Model.ScheduledDate" value="@Model.ScheduledDate.ToString(DATETIME_PICKER_FORMAT)">
                        <span asp-validation-for="@Model.ScheduledDate" class="text-danger"></span>
                    </div>
                    <input hidden asp-for="@Model.AwayTeamName" />
                    <input hidden asp-for="@Model.HomeTeamName" />
                    <input hidden asp-for="@Model.Id" />
                    <input hidden asp-for="@Model.PlayWeekId" />
                    <input hidden asp-for="@Model.AwayTeamId" />
                    <input hidden asp-for="@Model.HomeTeamId" />
                    <button type="submit" class="btn btn-primary btn-block mt-3"><i class="fas fa-plus-circle"></i>&nbsp;Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>