BESL.Web/Controllers/PlayersController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BESL.Application.Players.Queries.Details;
    using BESL.Application.Players.Queries.Invites;
    using BESL.Application.Players.Commands.AcceptInvite;
    using BESL.Application.Players.Commands.DeclineInvite;

    [Authorize]
    public class PlayersController : BaseController
    {
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
            => this.View(await this.Mediator.Send(new GetPlayerDetailsQuery() { Username = id }));

        public async Task<IActionResult> Invites()
            => this.View(await this.Mediator.Send(new GetInvitesForPlayerQuery()));

        [HttpPost]
        public async Task<IActionResult> AcceptInvite(AcceptInviteCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Invites));
        }

        [HttpPost]
        public async Task<IActionResult> DeclineInvite(DeclineInviteCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Invites));
        }
    }
}

BESL.Web/Controllers/SearchController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using BESL.Application.Search.Queries.QuerySearch;

    public class SearchController : BaseController
    {
        public async Task<IActionResult> Index([FromQuery]string query)
            => this.View(await this.Mediator.Send(new SearchQuery { Query = query }));
    }
}

BESL.Web/Controllers/TeamsController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    using BESL.Application.Teams.Commands.Create;
    using BESL.Application.Teams.Commands.Modify;
    using BESL.Application.Teams.Commands.InvitePlayer;
    using BESL.Application.Teams.Commands.RemovePlayer;
    using BESL.Application.Teams.Commands.TransferOwnership;
    using BESL.Application.Teams.Queries.Details;
    using BESL.Application.Teams.Queries.Modify;
    using BESL.Application.Teams.Queries.GetAllTeamsPaged;
    using BESL.Application.TournamentFormats.Queries.GetAllTournamentFormatsSelectList;
    using static BESL.SharedKernel.GlobalConstants;
    
    [Authorize]
    public class TeamsController : BaseController
    {
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery(Name = "p")]int? page)
        {
            page = (page ?? 1) - 1;

            // Results per page is intentionally used as a constant for testing purposes.
            // In a real life application, the user will be able to select the results
            // he wants to see on a given page.
            var query = new GetAllTeamsPagedQuery { Page = page.Value, PageSize = RESULTS_PER_PAGE_COUNT };

            var viewModel = await this.Mediator.Send(query);
            var pagedList = new StaticPagedList<TeamLookupModel>(
                viewModel.Teams,
                page.Value + 1,
                RESULTS_PER_PAGE_COUNT,
                viewModel.TotalTeamsCount);

            return this.View(pagedList);
        }

        public async Task<IActionResult> Create()
            => this.View(new CreateTeamCommand
            {
                Formats = await this.Mediator.Send(new GetAllTournamentFormatsSelectListQuery())
            });

        [HttpPost]
        public async Task<IActionResult> Create(CreateTeamCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                command.Formats = await this.Mediator.Send(new GetAllTournamentFormatsSelectListQuery());
                return this.View(command);
            }

            var teamId = await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new { Id = teamId });
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(GetTeamDetailsQuery query)
            => this.View(await this.Mediator.Send(query));

        public async Task<IActionResult> Modify(ModifyTeamQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> Modify(ModifyTeamCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(command);
            }

            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetTeamDetailsQuery { Id = command.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Invite(InvitePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Modify), new ModifyTeamQuery { Id = command.TeamId });
        }

        [HttpPost]
        public async Task<IActionResult> RemovePlayer(RemovePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Modify), new ModifyTeamQuery { Id = command.TeamId });
        }

        [HttpPost]
        public async Task<IActionResult> Leave(RemovePlayerCommand command)
        {
            await this.Mediator.Send(command);
            return this.LocalRedirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> TransferOwnership(TransferTeamOwnershipCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Details), new GetTeamDetailsQuery { Id = command.TeamId });
        }
    }
}

BESL.Web/Controllers/TournamentsController.cs
namespace BESL.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.Tournaments.Commands.Enroll;
    using BESL.Application.Tournaments.Queries.Details;
    using BESL.Application.Tournaments.Queries.Enroll;
    using BESL.Application.PlayWeeks.Queries.GetPlayWeeksForTournamentTable;

    [Authorize]
    public class TournamentsController : BaseController
    {
        [AllowAnonymous]
        public async Task<IActionResult> Details(GetTournamentDetailsQuery query)
            => this.View(await this.Mediator.Send(query));

        public async Task<IActionResult> Enroll(EnrollATeamQuery query)
            => this.View(await this.Mediator.Send(query));      

        [HttpPost]
        public async Task<IActionResult> Enroll(EnrollATeamCommand command)
        {
            if (this.ModelState.IsValid)
            {
                await this.Mediator.Send(command);
            }

            return this.RedirectToAction(nameof(Details), new GetTournamentDetailsQuery { Id = command.TournamentId });
        }

        [AllowAnonymous]
        public async Task<IActionResult> PlayWeeks(GetPlayWeeksForTournamentTableQuery query)
            => this.View(await this.Mediator.Send(query));
    }
}

BESL.Web/Views/Search/Index.cshtml
@model BESL.Application.Search.Queries.QuerySearch.SearchQueryViewModel
@{
    ViewData["Title"] = $"{Model.SearchQuery} - Search";
}

<div class="row mx-3 mb-3">
    <div class="col-md-12">
        <h4 class="display-4">Results for: "@Model.SearchQuery"</h4>
        <hr />
        <div class="mb-3">
            <h4 class="lead">Players:</h4>
            <ul>
                @if(Model.Players.Count() != 0)
                {
                    @foreach(var player in Model.Players)
                    {
                        <li><a asp-controller="Players" asp-action="Details" asp-route-id="@player.UserName"><h4>@player.UserName</h4></a></li>
                    }
                }
                else
                {
                    <li>No players found matching the criteria.</li>
                }
            </ul>
        </div>
        <div class="mb-3">
            <h4 class="lead">Teams:</h4>
            <ul>
                @if(Model.Teams.Count() != 0)
                {
                    @foreach(var team in Model.Teams)
                    {
                        <li><a asp-controller="Teams" asp-action="Details" asp-route-id="@team.Id"><h4>@team.Name</h4></a></li>
                    }
                }
                else
                {
                    <li>No teams found matching the criteria.</li>
                }
            </ul>
        </div>
        <div class="mb-3">
            <h4 class="lead">Tournaments:</h4>
            <ul>
                @if(Model.Tournaments.Count() != 0)
                {
                    @foreach(var tournament in Model.Tournaments)
                    {
                        <li><a asp-controller="Tournaments" asp-action="Details" asp-route-id="@tournament.Id"><h4>@tournament.Name</h4></a></li>
                    }
                }
                else
                {
                    <li>No tournaments found matching the criteria.</li>
                }
            </ul>
        </div>
    </div>
</div>