BESL.Web/Areas/Administration/Controllers/TournamentFormatsController.cs
namespace BESL.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.TournamentFormats.Commands.Create;
    using BESL.Application.TournamentFormats.Commands.Delete;
    using BESL.Application.TournamentFormats.Commands.Modify;
    using BESL.Application.TournamentFormats.Queries.GetAllTournamentFormats;
    using BESL.Application.TournamentFormats.Queries.Modify;
    using BESL.Application.Games.Queries.GetAllGamesSelectList;

    public class TournamentFormatsController : AdminController
    {
        public async Task<IActionResult> Create()
            => this.View(new CreateTournamentFormatCommand { Games = await this.Mediator.Send(new GetAllGamesSelectListQuery()) });

        [HttpPost]
        public async Task<IActionResult> Create(CreateTournamentFormatCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                command.Games = await this.Mediator.Send(new GetAllGamesSelectListQuery());
                return this.View(command);
            }

            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Modify(ModifyTournamentFormatQuery query)
            => this.View(await this.Mediator.Send(query));

        [HttpPost]
        public async Task<IActionResult> Modify(ModifyTournamentFormatCommand command)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(command);
            }

            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
            => this.View(await this.Mediator.Send(new GetAllTournamentFormatsQuery()));

        public async Task<IActionResult> Delete(DeleteTournamentFormatCommand command)
        {
            await this.Mediator.Send(command);
            return this.RedirectToAction(nameof(Index));
        }
    }
}

BESL.Web/Areas/Administration/Views/TournamentFormats/All.cshtml
@model BESL.Application.TournamentFormats.Queries.GetAll.GetAllTournamentFormatsQueryViewModel
@{
    Layout = null;
}
<div class="border rounded">
    <div class="container-fluid mt-2 mb-3">
        <form id="createFormatForm" data-ajax="true" data-ajax-loading="#spinner" data-ajax-url="/Administration/TournamentFormats/Create" data-ajax-method="GET" data-ajax-update="#formatsContentContainer"></form>
        <form id="refreshFormatForm" data-ajax="true" data-ajax-loading="#spinner" data-ajax-url="/Administration/TournamentFormats/All" data-ajax-method="GET" data-ajax-update="#formatsContentContainer"></form>
        <button class="btn btn-success mb-3" form="createFormatForm"><i class="fas fa-plus-circle"></i>&nbsp;Add a format</button>
        <button class="btn btn-primary mb-3" form="refreshFormatForm"><i class="fas fa-redo-alt"></i>&nbsp;Refresh formats list</button>
        <table class="table table-hover rounded shadow">
            <thead class="thead-dark rounded">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Game</th>
                    <th scope="col">Team players count</th>
                    <th scope="col">Total players</th>
                    <th scope="col" class="text-center"><i class="fas fa-cogs"></i></th>
                    <th scope="col" class="text-center"><i class="fas fa-trash-alt"></i></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.TournamentFormats.Count() > 0)
                {
                    @foreach (var tournamentFormat in Model.TournamentFormats)
                    {
                        <tr>
                            <th scope="row">@tournamentFormat.Id</th>
                            <td>@tournamentFormat.Name</td>
                            <td>@tournamentFormat.Game</td>
                            <td>@tournamentFormat.TeamPlayersCount</td>
                            <td>@tournamentFormat.TotalPlayersCount</td>
                            <td class="text-center">
                                <form data-ajax="true" data-ajax-loading="#spinner" data-ajax-url="Administration/TournamentFormats/Modify/@tournamentFormat.Id" data-ajax-method="GET" data-ajax-update="#formatsContentContainer">
                                    <button class="btn btn-info align-center"><i class="fas fa-wrench"></i>&nbsp;Modify</button>
                                </form>
                            </td>
                            <td class="text-center">
                                <form data-ajax="true" data-ajax-loading="#spinner" data-ajax-url="Administration/TournamentFormats/Delete/@tournamentFormat.Id?formatName=@tournamentFormat.Name" data-ajax-method="POST" data-ajax-confirm="Are you sure you want to delete @tournamentFormat.Name ?" data-ajax-update="#formatsContentContainer">
                                    <button class="btn btn-danger btn-"><i class="fas fa-times-circle"></i>&nbsp;Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="7" class="text-center"><h5>No tornament formats registered.</h5></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BESL.Web/Areas/Administration/Views/TournamentFormats/Create.cshtml
@model BESL.Application.TournamentFormats.Commands.Create.CreateTournamentFormatCommand
@{
    ViewData["ActivePage"] = ManageAdminNavPages.TournamentFormats;
    ViewData["Title"] = "Tournament formats";
}
<div class="border rounded container-fluid float-left col-lg-6">
    <div class="container-fluid mt-2 mb-3">
        <h2>Create a tournament format</h2>
        <form id="formatCreateForm" class="mb-3" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter name..." />
                <span asp-validation-for="Name" class="text-danger"></span>
                <small id="formatNameHelp" class="form-text text-muted">The format's title.</small>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea class="form-control" asp-for="Description" rows="5" placeholder="Enter description..."></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
                <small id="formatDescHelp" class="form-text text-muted">Description of the competitive format.</small>
            </div>
            <div class="form-group">
                <label asp-for="TeamPlayersCount">Players count per team</label>
                <input class="form-control" asp-for="TeamPlayersCount" placeholder="Enter team players count..." />
                <span asp-validation-for="TeamPlayersCount" class="text-danger"></span>
                <small id="formatPlayerCountHelp" class="form-text text-muted">Number of players per team, total count would be this value multiplied by two.</small>
            </div>
            <div class="form-group">
                <label asp-for="GameId">Game</label>
                <select class="form-control" asp-for="GameId" asp-items="@Model.Games.Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.Name }).ToList()"></select>
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-3"><i class="fas fa-plus-circle"></i>&nbsp;Submit</button>
        </form>
    </div>
</div>

BESL.Web/Areas/Administration/Views/TournamentFormats/Index.cshtml
@model BESL.Application.TournamentFormats.Queries.GetAllTournamentFormats.GetAllTournamentFormatsQueryViewModel
@{
    ViewData["ActivePage"] = ManageAdminNavPages.TournamentFormats;
    ViewData["Title"] = "Tournament formats";
}
<div class="border rounded">
    <div class="container-fluid mt-2 mb-3">
        <a asp-area="Administration" asp-controller="TournamentFormats" asp-action="Create" class="btn btn-success mb-3"><i class="fas fa-plus-circle"></i>&nbsp;Add a format</a>
        <table class="table table-hover rounded shadow">
            <thead class="thead-dark rounded">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Game</th>
                    <th scope="col">Team players count</th>
                    <th scope="col">Total players</th>
                    <th scope="col" class="text-center"><i class="fas fa-cogs"></i></th>
                    <th scope="col" class="text-center"><i class="fas fa-trash-alt"></i></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.TournamentFormats.Count() > 0)
                {
                    @foreach (var tournamentFormat in Model.TournamentFormats)
                    {
                        <tr>
                            <th scope="row" class="align-middle">@tournamentFormat.Id</th>
                            <td class="align-middle">@tournamentFormat.Name</td>
                            <td class="align-middle">@tournamentFormat.Game</td>
                            <td class="align-middle">@tournamentFormat.TeamPlayersCount</td>
                            <td class="align-middle">@tournamentFormat.TotalPlayersCount</td>
                            <td class="text-center">
                                <a asp-area="Administration" asp-controller="TournamentFormats" asp-action="Modify" asp-route-id="@tournamentFormat.Id" class="btn btn-info align-center"><i class="fas fa-wrench"></i>&nbsp;Modify</a>
                            </td>
                            <td class="text-center">
                                <form asp-area="Administration" asp-controller="TournamentFormats" asp-action="Delete" asp-route-id="@tournamentFormat.Id" onsubmit="return submitForm(this, '@(tournamentFormat.Name + " - " + tournamentFormat.Game)');">
                                    <button class="btn btn-danger btn-"><i class="fas fa-times-circle"></i>&nbsp;Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="7" class="text-center"><h5>No tornament formats registered.</h5></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    function submitForm(a, b) {
        return confirm(`Do you really want to delete ${b} ?`);
    }
</script>

BESL.Web/Areas/Administration/Views/TournamentFormats/Modify.cshtml
@model BESL.Application.TournamentFormats.Commands.Modify.ModifyTournamentFormatCommand
@{
    ViewData["ActivePage"] = ManageAdminNavPages.TournamentFormats;
    ViewData["Title"] = "Tournament formats";
}
<div class="border rounded container-fluid float-left col-lg-6">
    <div class="container-fluid mt-2 mb-3">
        <h2>Modify tournament format: @Model.GameName - @Model.Name (Id:@Model.Id)</h2>
        <form id="formatModifyForm" class="mb-3" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter name..." />
                <span asp-validation-for="Name" class="text-danger"></span>
                <small id="formatNameHelp" class="form-text text-muted">The format's title.</small>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea class="form-control" asp-for="Description" rows="5" placeholder="Enter description..."></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
                <small id="formatDescHelp" class="form-text text-muted">Description of the competitive format.</small>
            </div>
            <div class="form-group">
                <label asp-for="TeamPlayersCount">Players count per team</label>
                <input class="form-control" asp-for="TeamPlayersCount" placeholder="Enter team players count..." />
                <span asp-validation-for="TeamPlayersCount" class="text-danger"></span>
                <small id="formatPlayerCountHelp" class="form-text text-muted">Number of players per team, total count would be this value multiplied by two.</small>
            </div>           
            <div class="form-group">
                <label>Game</label>
                <select disabled class="form-control">
                    <option value=@Model.GameName>@Model.GameName</option>
                </select>
                <select hidden class="form-control" asp-for="@Model.GameName">
                    <option value=@Model.GameName></option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-3"><i class="fas fa-plus-circle"></i>&nbsp;Submit</button>
        </form>
    </div>
</div>