BESL.Web/Areas/Administration/Controllers/HomeController.cs
namespace BESL.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : AdminController
    {
        public IActionResult Index() => this.RedirectToAction("Index", "Games");
    }
}

BESL.Web/Components/CurrentWeekMatchesViewComponent.cs
namespace BESL.Web.Components
{
    using System.Threading.Tasks;

    using MediatR;
    using Microsoft.AspNetCore.Mvc;

    using BESL.Application.Matches.Queries.GetMatchesForCurrentPlayWeeks;

    public class CurrentWeekMatchesViewComponent : ViewComponent
    {
        private readonly IMediator mediator;

        public CurrentWeekMatchesViewComponent(IMediator mediator) => this.mediator = mediator;

        public async Task<IViewComponentResult> InvokeAsync()
            => this.View(await this.mediator.Send(new GetMatchesForCurrentPlayWeeksQuery()));
    }
}

BESL.Web/Controllers/HomeController.cs
namespace BESL.Web.Controllers
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using BESL.Web.Models;

    public class HomeController : BaseController
    {
        public IActionResult Index()
            => this.View();
        
        public IActionResult Privacy()
            => this.View();

        public IActionResult Error()
            => this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BESL.Web/Views/Home/Index.cshtml
@using static BESL.SharedKernel.GlobalConstants;
@{
    ViewData["Title"] = "Home Page";
}

@if (!this.User.Identity.IsAuthenticated)
{
    <div class="jumbotron">
        <h1 class="display-4">Welcome to BESL!</h1>
        <p class="lead">Bulgaria's leading platform for eSports!</p>
        <hr class="my-4">
        <p>Get your friends, create a team and join the upcoming tournaments! Play and reach the top of the tournament tables and get the chance to win some peripherall gear by our sponsors ThermalTake and Corsair!</p>
        <a class="btn btn-primary btn-lg" asp-page="/Account/Login" asp-area="Identity" role="button"><i class="fas fa-sign-in-alt"></i>&nbsp;Sign-in</a>
    </div>
}
<vc:front-page-active-tournaments></vc:front-page-active-tournaments>
<vc:current-week-matches></vc:current-week-matches>